event_index:
    path:     /event
    defaults: { _controller: "EventBundle:Event:index" }
    methods:  GET

event_show:
    path:     /event/{id}/show
    defaults: { _controller: "EventBundle:Event:show" }
    methods:  GET

event_new:
    path:     /event/new
    defaults: { _controller: "EventBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /event/{id}/edit
    defaults: { _controller: "EventBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /event/{id}/delete
    defaults: { _controller: "EventBundle:Event:delete" }
    methods:  DELETE