<?php

namespace NuseryBundle\Repository;

/**
 * revRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class revRepository extends \Doctrine\ORM\EntityRepository
{
}
