<?php

namespace NuseryBundle\Repository;

/**
 * revsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class revsRepository extends \Doctrine\ORM\EntityRepository
{
}
