# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Utilisateur\UtilisateurBundle\Entity\Utilisateur: sha512
    providers:
        main:
            id: fos_user.user_provider.username
        # in_memory:
           #  memory:
              #   users:
                 #    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                   #  admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider:     main
            pattern: ^/
            anonymous: true
            form_login:
                   login_path: fos_user_security_login
                   check_path: fos_user_security_check
            logout:
                   path: fos_user_security_logout
                   target: fos_user_security_login
            remember_me:
                    secret:     %secret% # %secret% est un paramètre de parameter
    role_hierarchy:
        # Un admin hérite des droits d'auteur et de modérateur
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        # On garde ce rôle superadmin, il nous resservira par la suite
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
