<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9fm7slg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9fm7slg/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9fm7slg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9fm7slg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9fm7slg\appProdProjectContainer(array(
    'container.build_hash' => '9fm7slg',
    'container.build_id' => 'b208f7e3',
    'container.build_time' => 1543800308,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9fm7slg');
