<?php

namespace EventBundle\Repository;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends \Doctrine\ORM\EntityRepository
{
    public function getuserdata($idEvent ,$idUser)
    {
        $query = $this->getEntityManager()
            ->createQuery("select a from EventBundle:Participant a  WHERE (a.idE=:idEvent) AND (a.idU=:idUser)")
            ->setParameters(array('idUser'=> $idUser, 'idEvent' => $idEvent)); //très important! parameterS
        return $query->getResult();

    }
}
