<?php

namespace PlantBundle\Repository;

/**
 * PlantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM PlantBundle:Plant p ORDER BY p.plantname ASC'
            )
            ->getResult();
    }
    public function findAllByPlantName($plantname)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT p FROM PlantBundle:Plant p  WHERE p.plantname LIKE :plant")
            ->setParameter('plant','%'.$plantname.'%')
            ->getResult();
    }
}
