<?php

namespace PlantBundle\Repository;
use PlantBundle\Entity\Userplant;

/**
 * PlantmaintainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantmaintainingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserplantOrderedByDate(Userplant $userplant)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM PlantBundle:Plantmaintaining p JOIN p.userplant u WHERE u.id='.$userplant->getId().' ORDER BY p.date ASC'
            )
            ->getResult();
    }
}
