<?php

namespace PlantBundle\Repository;

/**
 * UserplantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserplantRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM PlantBundle:Userplant p ORDER BY p.name ASC'
            )
            ->getResult();
    }
    public function findAllByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM PlantBundle:Userplant p JOIN p.user u WHERE u.id ='.$user->getId()
            )
            ->getResult();
    }
    public function findMyPlants($user)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM PlantBundle:Userplant p JOIN p.user u WHERE u.id ='.$user->getId()
            )
            ->getResult();
    }
    public function coutExistNames($name)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(p.name) PlantBundle:Userplant p WHERE p.name='.$name
            )
            ->getSingleScalarResult();
    }
}
