admin_index:
    path:     /
    defaults: { _controller: "EcommerceEcommerceBundle:ProduitAdmin:index" }
    methods:  GET

admin_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceEcommerceBundle:ProduitAdmin:show" }
    methods:  GET

admin_new:
    path:     /new
    defaults: { _controller: "EcommerceEcommerceBundle:ProduitAdmin:new" }
    methods:  [GET, POST]

admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceEcommerceBundle:ProduitAdmin:edit" }
    methods:  [GET, POST]

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceEcommerceBundle:ProduitAdmin:delete" }
    methods:  DELETE
