<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS4xth4c\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS4xth4c/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerS4xth4c.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerS4xth4c\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerS4xth4c\appDevDebugProjectContainer(array(
    'container.build_hash' => 'S4xth4c',
    'container.build_id' => '466a29b3',
    'container.build_time' => 1577727963,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerS4xth4c');
