<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function byFacture($utilisateur)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('u.utilisateur = :utilisateur')
            ->andWhere('c.valider = 1')
            ->andWhere('c.reference != 0')
            ->orderBy('c.id')
            ->setParameter('utilisateur', $utilisateur);

        return $qb->getQuery()->getResult();
    }
}
