<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByarrayid($array)
    {
        $qb = $this->createQueryBuilder('p')
            ->Select('p')
            ->Where('p.id IN (:array)')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }

      public function Bycategorie($cat)
                 {

   $qb= $this->createQueryBuilder('p')
          ->where('p.categoriee=:cat')
           ->setParameter('cat',$cat)
          ->andWhere('p.disponible=1')
          ->orderBy('p.id');
    return $qb->getQuery()
               ->getResult();
                   }

    public function findbychaine($chaine)
    {

        $qb= $this->createQueryBuilder('p')
            ->where('p.nom like :chaine')
            ->setParameter('chaine',"%".$chaine."%")
            ->andWhere('p.disponible=1')
           ->orderBy('p.id');
        return $qb->getQuery()
            ->getResult();
    }

    public function findbyid($id)
    {
        $qb= $this->createQueryBuilder('p')
            ->where('p.id = :id')
            ->setParameter('id',$id);

        return $qb->getQuery()
            ->getResult();
    }
    public function findbycat($categorie)
    {
        $qb= $this->createQueryBuilder('p')
            ->where('p.categorie = :id')
            ->setParameter('id',$categorie);

        return $qb->getQuery()
            ->getResult();
    }

}
